---
title: "quiz 2"
author: "yufree"
date: "2014年9月15日"
output: html_document
---

# 1

```{r}
library(tm)
library(stringi)
enb <- stri_read_lines('data/final/en_US/en_US.blogs.txt',locale = "en")
lowerenb <- stri_trans_tolower(enb)
quiz21 <- lowerenb[grepl('case',lowerenb)]
enb.vec <- VectorSource(quiz21)
enb <- Corpus(enb.vec)
enblog.tdm <- TermDocumentMatrix(enb)
BigramTokenizer <- function(x) {RWeka::NGramTokenizer(x, RWeka::Weka_control(min = 3, max = 3))}
bdm <- TermDocumentMatrix(enb, control = list(tokenize = BigramTokenizer))
case <- bdm$dimnames$Terms[grepl('case of',bdm$dimnames$Terms)]
m = as.matrix(bdm[case,])
v = sort(rowSums(m), decreasing = TRUE)
```

# 2

```{r, echo=FALSE}
quiz22 <- lowerenb[grepl('struggling',lowerenb)]
enb.vec <- VectorSource(quiz22)
enb <- Corpus(enb.vec)
enblog.tdm <- TermDocumentMatrix(enb)
BigramTokenizer <- function(x) {RWeka::NGramTokenizer(x, RWeka::Weka_control(min = 3, max = 3))}
bdm <- TermDocumentMatrix(enb, control = list(tokenize = BigramTokenizer))
case <- bdm$dimnames$Terms[grepl('mean the',bdm$dimnames$Terms)]
m = as.matrix(bdm[case,])
v = sort(rowSums(m), decreasing = TRUE)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
